# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: My test 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  foo:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      version: ${{ steps.foo.outputs.version }}
    steps:
    - id: foo
      run: echo "::set-output name=version::hello"
  job2:
    runs-on: ubuntu-latest
    needs: foo
    steps:
    - run: echo ${{needs.foo.outputs.version}}
